server:
  port: 5004
spring:
  application:
    name: cloud-account

persistence:
  mybatis:
    jdbc:
      driver: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/mxcg_cloud?useUnicode=true&characterEncoding=utf8&useSSL=false
      username: root
      password: root
mybatis-plus:
    mapper-locations:mapper/*.xml
    configuration:
        use-column-label:true
        auto-mapping-behavior:full
        map-underscore-to-camel-case:true

logging.level.org.springframework.security: DEBUG
