server:
  port: 5004
spring:
  application:
    name: cloud-account


  datasource:
    url: jdbc:mysql://localhost:3306/mxcg_cloud?useSSL=false&amp;characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  hikari:
    minIdle: 10
    idle-timeout: 10000
    maximumPoolSize: 30

logging.level.org.springframework.security: DEBUG
