


server:
  port: 5004
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mxcg_cloud??useSSL=false&amp;characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  hikari:
    minIdle: 10
    idle-timeout: 10000
    maximumPoolSize: 30
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
  application:
      name:cloud-account
