spring:
 application:
  name: cloud-author
  
server:
  port: 5005


 persistence:
  mybatis:
    jdbc:
      driver: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/mxcg_cloud?useUnicode=true&characterEncoding=utf8&useSSL=false
      username: root
       password: root


logging.level.org.springframework.security: DEBUG
security:
  oauth2:
    clientId: cloud
    clientSecret: cloud
    scope: webapp
