spring:
 application:
  name: cloud-author
  
  
server:
  port: 5005
  
  spring:
  	datasource:
  		url: jdbc:mysql://localhost:3306/zoucloud?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false
  	username: root
  	password: root
  	driver-class-name: com.mysql.jdbc.Driver


logging.level.org.springframework.security: DEBUG
