spring:
 application:
  name: cloud-author
  
server:
  port: 5005

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost/zoucloud?useSSL=false&characterEncoding=utf-8&serverTimezone=Asia/Shanghai

logging.level.org.springframework.security: DEBUG
