server:
  port: 5005


spring:
  datasource:
  url: jdbc:mysql://localhost:3306/zoucloud?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false
  username: root
  password: root
  driver-class-name: com.mysql.jdbc.Driver
 hikari:
  minIdle: 10
  idle-timeout: 10000
  maximumPoolSize: 30
  


logging.level.org.springframework.security: DEBUG
