spring:
 application:
  name: cloud-author
  
server:
  port: 5005


 


logging.level.org.springframework.security: DEBUG
security:
  oauth2:
    clientId: cloud
    clientSecret: cloud
    scope: webapp
