spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name:com.mysql.cj.jdbc.Driver
    url:jdbc:mysql://localhost/zoucloud?useSSL=false&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username:root
    password:root

  application:
    name:cloud-author
   
server:
  port:5005


   
logging.level.org.springframework.security: TRACE
