spring:
 application:
  name: cloud-author
  
server:
  port: 5005

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/zoucloud?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8

logging.level.org.springframework.security: DEBUG
security:
  oauth2:
    clientId: cloud
    clientSecret: cloud
    scope: webapp
