
spring:
 application:
  name: GatewayApi
  
server:
  port: 5002

# 网关配置
zuul:
  # 公共前缀
  prefix: /api
  # 路由转发规则
  routes:
    cloud-account:
      path: /uc/uc/**
      sensitiveHeaders:
      service-id: cloud-account
    cloud-author:
      path: /auth/**
      sensitiveHeaders:
      service-id: cloud-author
    baidu:
      path: /baidu/**
      sensitiveHeaders:
      url: http://baidu.com
  add-proxy-headers: true
  ignoredServices: '*'

# 权限认证
security:
  sessions: stateless # 无状态
  oauth2:
    resource:
      loadBalanced: true # 负载均衡
      token-info-uri: http://cloud-author/oauth/check_token
      user-info-uri: http://cloud-author/user
      prefer-token-info: false
      service-id: cloud-gateway
  excludeUrls: 
    - /api/auth/**
logging.level.org.springframework.security: TRACE
